MagisAir/CrewAssignments/urls.py
from django.urls import path

from. views import (CrewMemberListView, CrewRoleListView,
                    CrewAssignmentListView, CrewAssignmentCreateView,
                    CrewAssignmentDetailView, CrewRoleCreateView,
                    CrewRoleDetailView, CrewMemberCreateView,
                    CrewMemberDetailView, SQL_Query2)

urlpatterns = [
    path('members', CrewMemberListView.as_view(), name='crewMember-table'),
    path('roles', CrewRoleListView.as_view(), name='crewRole-table'),
    path('assignments', CrewAssignmentListView.as_view(), name='crewAssignment-table'),
    path('members/add', CrewMemberCreateView.as_view(), name='crewMember-add'),
    path('roles/add', CrewRoleCreateView.as_view(), name='crewRole-add'),
    path('assignments/add', CrewAssignmentCreateView.as_view(), name='crewAssignment-add'),
    path('members/<pk>_added', CrewMemberDetailView.as_view(), name='added-member'),
    path('roles/<pk>_added', CrewRoleDetailView.as_view(), name='added-role'),
    path('assignments/<pk>_added', CrewAssignmentDetailView.as_view(), name='added-assignment'),
    path('SQLQuery2', SQL_Query2, name='SQL_Query2')
]

app_name='CrewAssignments'

MagisAir/FlightBooking/urls.py
from django.urls import path

from. views import (AdditionalitemListView, BookingAdditionalitemListView,
                    BookingListView, PassengerListView, AdditionalitemCreateView,
                    BookingAdditionalitemCreateView, BookingCreateView, PassengerCreateView,
                    AdditionalitemDetailview, BookingAdditionalitemDetailview, BookingDetailView,
                    PassengerDetailview)

urlpatterns = [
    path('passengers', PassengerListView.as_view(), name='passenger-table'),
    path('bookings', BookingListView.as_view(), name='booking-table'),
    path('addItems', AdditionalitemListView.as_view(), name='addItem-table'),
    path('bookingAddItems', BookingAdditionalitemListView.as_view(), name='bookingAddItem-table'),
    path('passengers/add', PassengerCreateView.as_view(), name='passenger-add'),
    path('bookings/add', BookingCreateView.as_view(), name='booking-add'),
    path('addItems/add', AdditionalitemCreateView.as_view(), name='addItem-add'),
    path('bookingAddItems/add', BookingAdditionalitemCreateView.as_view(), name='bookingAddItem-add'),
    path('passengers/<pk>_added', PassengerDetailview.as_view(), name='added-passenger'),
    path('bookings/<pk>_added', BookingDetailView.as_view(), name='added-booking'),
    path('addItems/<pk>_added', AdditionalitemDetailview.as_view(), name='added-addItem'),
    path('bookingAddItems/<pk>_added', BookingAdditionalitemDetailview.as_view, name='added-bookingAddItem')
]

app_name='FlightBooking'

MagisAir/FlightRoutes/urls.py
from django.urls import path

from. views import (LocationListView, FlightListView, RouteListView,
                    LocationCreateView, FlightCreateView, RouteCreateView,
                    LocationDetailview, FlightDetailView, RouteDetailView,
                    SQL_Query1)

urlpatterns = [
    path('locations', LocationListView.as_view(), name='location-table'),
    path('flights', FlightListView.as_view(), name='flight-table'),
    path('routes', RouteListView.as_view(), name='route-table'),
    path('locations/add', LocationCreateView.as_view(), name='location-add'),
    path('flights/add', FlightCreateView.as_view(), name='flight-add'),
    path('routes/add', RouteCreateView.as_view(), name='route-add'),
    path('locations/<pk>_added', LocationDetailview.as_view(), name='added-location'),
    path('flights/<pk>_added', FlightDetailView.as_view(), name='added-flight'),
    path('routes/<pk>_added', RouteDetailView.as_view(), name='added-route'),
    path('SQL_Query1', SQL_Query1, name='SQL_Query1')
]

app_name='FlightRoutes'

MagisAir/MagisAir/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('flights/', include('flights.urls', namespace='flights')),
    path('CrewAssignments/', include('CrewAssignments.urls', namespace='CrewAssignments')),
    path('FlightRoutes/', include('FlightRoutes.urls', namespace='FlightRoutes')),
    path('FlightBooking/', include('FlightBooking.urls', namespace='FlightBooking')),
    path('admin/', admin.site.urls),
]

MagisAir/flights/urls.py
from django.urls import path

from. views import index

urlpatterns = [
    path('', index, name='index')
]

app_name='flights'

MagisAir/CrewAssignments/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Flight(models.Model):
    flight_id = models.CharField(primary_key=True, max_length=10)
    flt_route = models.ForeignKey('FlightRoutes.Route', models.DO_NOTHING, related_name='route')
    flt_datetime_departure = models.DateTimeField()
    flt_datetime_arrival = models.DateTimeField()

    def __str__(self):
        return '{}'.format(self.flight_id)

    class Meta:
        managed = False
        db_table = 'flight'

class CrewMember(models.Model):
    crew_id = models.AutoField(primary_key=True)
    crw_lname = models.CharField(max_length=255)
    crw_fname = models.CharField(max_length=255)

    def __str__(self):
        return '{}'.format(self.crew_id)
    
    def get_absolute_url(self):
        return reverse('CrewAssignments:added-member', kwargs={'pk': self.pk})

    class Meta:
        managed = False
        db_table = 'crew_member'

class Role(models.Model):
    role_id = models.AutoField(primary_key=True)
    rle_title = models.CharField(max_length=255)
    rle_desc = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.role_id)
    
    def get_absolute_url(self):
        return reverse('CrewAssignments:added-role', kwargs={'pk': self.pk})

    class Meta:
        managed = False
        db_table = 'role'

class CrewAssignment(models.Model):
    cas_crew = models.OneToOneField('CrewMember', models.DO_NOTHING,related_name='+', primary_key=True)
    cas_flight = models.ForeignKey('Flight', models.DO_NOTHING, related_name='+')
    cas_role = models.ForeignKey('Role', models.DO_NOTHING, related_name='+')

    def get_absolute_url(self):
        return reverse('CrewAssignments:added-assignment', kwargs={'pk': self.pk})

    class Meta:
        managed = False
        db_table = 'crew_assignment'
        unique_together = (('cas_crew_id', 'cas_flight_id', 'cas_role_id'),)

MagisAir/CrewAssignments/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from .models import CrewAssignment, CrewMember, Role

def SQL_Query2(request):
    members = CrewMember.objects.raw("SELECT crew_id, CONCAT(crew_member.crw_lname, ', ', crew_member.crw_fname) AS Crew, role.rle_title AS Role, flight.flight_id AS Flight, location.loc_name AS Destination, flight.flt_datetime_departure AS Departure, flight.flt_datetime_arrival AS Arrival FROM crew_member, crew_assignment, role, flight, route, location WHERE crew_assignment.cas_crew_id = crew_member.crew_id AND crew_assignment.cas_role_id = role.role_id AND crew_assignment.cas_flight_id = flight.flight_id AND flight.flt_route_id = route.route_id AND route.rt_destination = location.location_id;")
    print(members)
    return render(request, 'CrewAssignments/SQL_Query2.html', {'data': members})

class CrewMemberListView(ListView):
    model = CrewMember
    def get(self, request):
        crewMembers = CrewMember.objects.all()
        return render(request, 'CrewAssignments/members.html', {
            'crewMembers': crewMembers
        })

class CrewRoleListView(ListView):
    model = Role
    def get(self, request):
        crewRoles = Role.objects.all()
        return render(request, 'CrewAssignments/roles.html', {
            'crewRoles': crewRoles
        })

class CrewAssignmentListView(ListView):
    model = CrewAssignment
    def get(self, request):
        crewAssignments = CrewAssignment.objects.all()
        return render(request, 'CrewAssignments/assignments.html', {
            'crewAssignments': crewAssignments
        })
    
class CrewMemberCreateView(CreateView):
    model = CrewMember
    fields = '__all__'
    template_name = 'CrewAssignments/membersCreate.html'

class CrewRoleCreateView(CreateView):
    model = Role
    fields = '__all__'
    template_name = 'CrewAssignments/rolesCreate.html'

class CrewAssignmentCreateView(CreateView):
    model = CrewAssignment
    fields = '__all__'
    template_name = 'CrewAssignments/assignmentsCreate.html'

class CrewMemberDetailView(DetailView):
    model = CrewMember
    template_name = 'CrewAssignments/successfullyAdded.html'

class CrewRoleDetailView(DetailView):
    model = Role
    template_name = 'CrewAssignments/successfullyAdded.html'

class CrewAssignmentDetailView(DetailView):
    model = CrewAssignment
    template_name = 'CrewAssignments/successfullyAdded.html'

MagisAir/CrewAssignments/templates/CrewAssignments/SQL_Query2.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Functionality {% endblock %}
{% block content %}
<h1>CREW ASSIGNMENTS FUNCTIONALITY </h1>
<table>
    <tr>
        <th>Crew</th>
        <th>Role</th>
        <th>Flight</th>
        <th>Destination</th>
        <th>Departure</th>
        <th>Arrival</th>
    </tr>
    {% for i in data %}
    <tr>
        <td>{{ i.Crew }}</td>
        <td>{{ i.Role }}</td>
        <td>{{ i.Flight }}</td>
        <td>{{ i.Destination }}</td>
        <td>{{ i.Departure }}</td>
        <td>{{ i.Arrival }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'CrewAssignments:crewRole-table'%}">Check Roles</a></p>
{% endblock %} 

MagisAir/CrewAssignments/templates/CrewAssignments/assignments.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Crew Assignments {% endblock %}
{% block content %}
<h1>MAGIS Air Crew Assignments</h1>
<table>
    <tr>
        <th>Crew ID</th>
        <th>Flight ID</th>
        <th>Route ID</th>
    </tr>
    {% for object in crewAssignments %}
    <tr>
        <td><a href="{%url 'CrewAssignments:crewMember-table'%}">{{ object.cas_crew_id }}</a></td>
        <td><a href="{%url 'FlightRoutes:flight-table'%}">{{ object.cas_flight_id }}</a></td>
        <td><a href="{%url 'CrewAssignments:crewRole-table'%}">{{ object.cas_role_id }}</a></td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'CrewAssignments:crewAssignment-add' %}">Add Assignment</a></p>
<p><a href="{%url 'CrewAssignments:crewMember-table'%}">Check Members</a></p>
<p><a href="{%url 'CrewAssignments:crewRole-table'%}">Check Roles</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
<p><a href="{%url 'CrewAssignments:SQL_Query2'%}">Check Out Crew Assignments Functionality</a></p>
{% endblock %} 

MagisAir/CrewAssignments/templates/CrewAssignments/assignmentsCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add an Assignment {% endblock %} 
{% block content %}
    <h1>Add a New Assignment</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Assignment">
    </form>
{% endblock %}

MagisAir/CrewAssignments/templates/CrewAssignments/members.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Crew Members {% endblock %}
{% block content %}
<h1>MAGIS Air Crew Members</h1>
<table>
    <tr>
        <th>Crew ID</th>
        <th>First Name</th>
        <th>Last Name</th>
    </tr>
    {% for object in crewMembers %}
    <tr>
        <td>{{ object.crew_id }}</td>
        <td>{{ object.crw_fname }}</td>
        <td>{{ object.crw_lname }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'CrewAssignments:crewMember-add' %}">Add Member</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'CrewAssignments:crewRole-table'%}">Check Roles</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
<p><a href="{%url 'CrewAssignments:SQL_Query2'%}">Check Out Crew Assignments Functionality</a></p>
{% endblock %} 

MagisAir/CrewAssignments/templates/CrewAssignments/membersCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add a Crew Member {% endblock %} 
{% block content %}
    <h1>Add a New Crew Member</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Member">
    </form>
{% endblock %}

MagisAir/CrewAssignments/templates/CrewAssignments/roles.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Crew Roles {% endblock %}
{% block content %}
<h1>MAGIS Air Crew Roles</h1>
<table>
    <tr>
        <th>Crew ID</th>
        <th>First Name</th>
        <th>Last Name</th>
    </tr>
    {% for object in crewRoles %}
    <tr>
        <td>{{ object.role_id }}</td>
        <td>{{ object.rle_title }}</td>
        <td>{{ object.rle_desc }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'CrewAssignments:crewRole-add' %}">Add Role</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'CrewAssignments:crewMember-table'%}">Check Members</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
<p><a href="{%url 'CrewAssignments:SQL_Query2'%}">Check Out Crew Assignments Functionality</a></p>
{% endblock %} 

MagisAir/CrewAssignments/templates/CrewAssignments/rolesCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add a Role {% endblock %} 
{% block content %}
    <h1>Add a New Role</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Role">
    </form>
{% endblock %}

MagisAir/CrewAssignments/templates/CrewAssignments/successfullyAdded.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air {% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'details_style.css' %}">
<h1>Your Data was successfully added</h1>
</table>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'CrewAssignments:crewMember-table'%}">Check Members</a></p>
<p><a href="{%url 'CrewAssignments:crewRole-table'%}">Check Roles</a></p>
{% endblock %} 