MagisAir/CrewAssignments/urls.py
from django.urls import path

from. views import (CrewMemberListView, CrewRoleListView,
                    CrewAssignmentListView, CrewAssignmentCreateView,
                    CrewAssignmentDetailView, CrewRoleCreateView,
                    CrewRoleDetailView, CrewMemberCreateView,
                    CrewMemberDetailView, SQL_Query2)

urlpatterns = [
    path('members', CrewMemberListView.as_view(), name='crewMember-table'),
    path('roles', CrewRoleListView.as_view(), name='crewRole-table'),
    path('assignments', CrewAssignmentListView.as_view(), name='crewAssignment-table'),
    path('members/add', CrewMemberCreateView.as_view(), name='crewMember-add'),
    path('roles/add', CrewRoleCreateView.as_view(), name='crewRole-add'),
    path('assignments/add', CrewAssignmentCreateView.as_view(), name='crewAssignment-add'),
    path('members/<pk>_added', CrewMemberDetailView.as_view(), name='added-member'),
    path('roles/<pk>_added', CrewRoleDetailView.as_view(), name='added-role'),
    path('assignments/<pk>_added', CrewAssignmentDetailView.as_view(), name='added-assignment'),
    path('SQLQuery2', SQL_Query2, name='SQL_Query2')
]

app_name='CrewAssignments'

MagisAir/FlightBooking/urls.py
from django.urls import path

from. views import (AdditionalitemListView, BookingAdditionalitemListView,
                    BookingListView, PassengerListView, AdditionalitemCreateView,
                    BookingAdditionalitemCreateView, BookingCreateView, PassengerCreateView,
                    AdditionalitemDetailview, BookingAdditionalitemDetailview, BookingDetailView,
                    PassengerDetailview)

urlpatterns = [
    path('passengers', PassengerListView.as_view(), name='passenger-table'),
    path('bookings', BookingListView.as_view(), name='booking-table'),
    path('addItems', AdditionalitemListView.as_view(), name='addItem-table'),
    path('bookingAddItems', BookingAdditionalitemListView.as_view(), name='bookingAddItem-table'),
    path('passengers/add', PassengerCreateView.as_view(), name='passenger-add'),
    path('bookings/add', BookingCreateView.as_view(), name='booking-add'),
    path('addItems/add', AdditionalitemCreateView.as_view(), name='addItem-add'),
    path('bookingAddItems/add', BookingAdditionalitemCreateView.as_view(), name='bookingAddItem-add'),
    path('passengers/<pk>_added', PassengerDetailview.as_view(), name='added-passenger'),
    path('bookings/<pk>_added', BookingDetailView.as_view(), name='added-booking'),
    path('addItems/<pk>_added', AdditionalitemDetailview.as_view(), name='added-addItem'),
    path('bookingAddItems/<pk>_added', BookingAdditionalitemDetailview.as_view, name='added-bookingAddItem')
]

app_name='FlightBooking'

MagisAir/FlightRoutes/urls.py
from django.urls import path

from. views import (LocationListView, FlightListView, RouteListView,
                    LocationCreateView, FlightCreateView, RouteCreateView,
                    LocationDetailview, FlightDetailView, RouteDetailView,
                    SQL_Query1)

urlpatterns = [
    path('locations', LocationListView.as_view(), name='location-table'),
    path('flights', FlightListView.as_view(), name='flight-table'),
    path('routes', RouteListView.as_view(), name='route-table'),
    path('locations/add', LocationCreateView.as_view(), name='location-add'),
    path('flights/add', FlightCreateView.as_view(), name='flight-add'),
    path('routes/add', RouteCreateView.as_view(), name='route-add'),
    path('locations/<pk>_added', LocationDetailview.as_view(), name='added-location'),
    path('flights/<pk>_added', FlightDetailView.as_view(), name='added-flight'),
    path('routes/<pk>_added', RouteDetailView.as_view(), name='added-route'),
    path('SQL_Query1', SQL_Query1, name='SQL_Query1')
]

app_name='FlightRoutes'

MagisAir/MagisAir/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('flights/', include('flights.urls', namespace='flights')),
    path('CrewAssignments/', include('CrewAssignments.urls', namespace='CrewAssignments')),
    path('FlightRoutes/', include('FlightRoutes.urls', namespace='FlightRoutes')),
    path('FlightBooking/', include('FlightBooking.urls', namespace='FlightBooking')),
    path('admin/', admin.site.urls),
]

MagisAir/flights/urls.py
from django.urls import path

from. views import index

urlpatterns = [
    path('', index, name='index')
]

app_name='flights'

MagisAir/FlightRoutes/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Flight(models.Model):
    flight_id = models.CharField(primary_key=True, max_length=10)
    flt_route = models.ForeignKey('Route', models.DO_NOTHING, related_name='+')
    flt_datetime_departure = models.DateTimeField()
    flt_datetime_arrival = models.DateTimeField()

    def __str__(self):
        return '{}'.format(self.flight_id)

    def get_absolute_url(self):
        return reverse('FlightRoutes:added-flight', kwargs={'pk': self.pk})
    
    class Meta:
        managed = False
        db_table = 'flight'

class Location(models.Model):
    location_id = models.AutoField(primary_key=True)
    loc_name = models.CharField(max_length=255)

    def __str__(self):
        return '{}'.format(self.location_id)
    
    def get_absolute_url(self):
        return reverse('FlightRoutes:added-location', kwargs={'pk': self.pk})

    class Meta:
        managed = False
        db_table = 'location'

class Route(models.Model):
    route_id = models.AutoField(primary_key=True)
    rt_origin = models.ForeignKey(Location, models.DO_NOTHING, db_column='rt_origin', related_name='+')
    rt_destination = models.ForeignKey(Location, models.DO_NOTHING, db_column='rt_destination')
    rt_price = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.route_id)
    
    def get_absolute_url(self):
        return reverse('FlightRoutes:added-route', kwargs={'pk': self.pk})

    class Meta:
        managed = False
        db_table = 'route'

MagisAir/flights/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Additionalitem(models.Model):
    additionalitem_id = models.AutoField(primary_key=True)
    aitm_item = models.CharField(max_length=255)
    aitm_itemdesc = models.CharField(max_length=255, blank=True, null=True)
    aitm_cost = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'additionalitem'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Booking(models.Model):
    bkg_passenger = models.OneToOneField('Passenger', models.DO_NOTHING, primary_key=True)
    bkg_flight = models.ForeignKey('Flight', models.DO_NOTHING)
    bkg_bookingdate = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'booking'
        unique_together = (('bkg_passenger', 'bkg_flight'),)


class BookingAdditionalitem(models.Model):
    bai_passenger = models.OneToOneField(Booking, models.DO_NOTHING, primary_key=True)
    bai_flight = models.ForeignKey(Booking, models.DO_NOTHING)
    bai_additionalitem = models.ForeignKey(Additionalitem, models.DO_NOTHING)
    bai_quantity = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'booking_additionalitem'
        unique_together = (('bai_passenger', 'bai_flight', 'bai_additionalitem'),)


class CrewAssignment(models.Model):
    cas_crew_id = models.IntegerField(primary_key=True)
    cas_flight_id = models.CharField(max_length=10)
    cas_role_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'crew_assignment'
        unique_together = (('cas_crew_id', 'cas_flight_id', 'cas_role_id'),)


class CrewMember(models.Model):
    crew_id = models.AutoField(primary_key=True)
    crw_lname = models.CharField(max_length=255)
    crw_fname = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'crew_member'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Flight(models.Model):
    flight_id = models.CharField(primary_key=True, max_length=10)
    flt_route = models.ForeignKey('Route', models.DO_NOTHING)
    flt_datetime_departure = models.DateTimeField()
    flt_datetime_arrival = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'flight'


class Location(models.Model):
    location_id = models.AutoField(primary_key=True)
    loc_name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'location'


class Passenger(models.Model):
    passenger_id = models.AutoField(primary_key=True)
    pax_lname = models.CharField(max_length=255)
    pax_fname = models.CharField(max_length=255)
    pax_birthdate = models.DateField()
    pax_gender = models.CharField(max_length=2)

    class Meta:
        managed = False
        db_table = 'passenger'


class Role(models.Model):
    role_id = models.AutoField(primary_key=True)
    rle_title = models.CharField(max_length=255)
    rle_desc = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'role'


class Route(models.Model):
    route_id = models.AutoField(primary_key=True)
    rt_origin = models.ForeignKey(Location, models.DO_NOTHING, db_column='rt_origin')
    rt_destination = models.ForeignKey(Location, models.DO_NOTHING, db_column='rt_destination')
    rt_price = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'route'

MagisAir/FlightRoutes/forms.py
from django import forms
from .models import Location, Flight, Route

class LocationForm(forms.ModelForm):
    class meta:
        model = Location
        fields = ['location_id',
                'loc_name' ]

class FlightForm(forms.ModelForm):
    class meta:
        model = Flight
        fields = ['flight_id', 'flt_route',
                'flt_datetime_departure', 'flt_datetime_arrival']

class RouteForm (forms.ModelForm):
    class meta:
        model = Route
        fields = ['route_id', 'rt_origin',
                'rt_destination', 'rt_price']

MagisAir/FlightRoutes/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from .models import Flight, Location, Route

def SQL_Query1(request):
    flights = Flight.objects.raw("SELECT flight.flight_id, origin.loc_name Origin, destination.loc_name Destination, flight.flt_datetime_departure AS Departure, flight.flt_datetime_arrival AS Arrival, CONCAT(HOUR(TIMEDIFF(flight.flt_datetime_arrival, flight.flt_datetime_departure)), ' hours ', MINUTE(TIMEDIFF(flight.flt_datetime_arrival, flight.flt_datetime_departure)), ' minutes') Duration FROM flight, route, location origin, location destination WHERE flight.flt_route_id = route.route_id AND route.rt_origin = origin.location_id AND route.rt_destination = destination.location_id;")
    print(flights)
    return render(request, 'FlightRoutes/SQL_Query1.html', {'data': flights})

class LocationListView(ListView):
    model = Location
    def get(self, request):
        locations = Location.objects.all()
        return render(request, 'FlightRoutes/locations.html', {
            'locations': locations
        })

class FlightListView(ListView):
    model = Flight
    def get(self, request):
        flights = Flight.objects.all()
        return render(request, 'FlightRoutes/flights.html', {
            'flights': flights
        })

class RouteListView(ListView):
    model = Route
    def get(self, request):
        routes = Route.objects.all()
        return render(request, 'FlightRoutes/routes.html', {
            'routes': routes
        })

class LocationCreateView(CreateView):
    model = Location
    fields = '__all__'
    template_name = 'FlightRoutes/locationsCreate.html'

class FlightCreateView(CreateView):
    model = Flight
    fields = '__all__'
    template_name = 'FlightRoutes/flightsCreate.html'

class RouteCreateView(CreateView):
    model = Route
    fields = '__all__'
    template_name = 'FlightRoutes/routesCreate.html'

class LocationDetailview(DetailView):
    model = Location
    template_name = 'FlightRoutes/successfullyAdded.html'

class FlightDetailView(DetailView):
    model = Flight
    template_name = 'FlightRoutes/successfullyAdded.html'

class RouteDetailView(DetailView):
    model = Route
    template_name = 'FlightRoutes/successfullyAdded.html'

MagisAir/flights/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse('Welcome to MagisAir Database')

MagisAir/FlightRoutes/templates/FlightRoutes/SQL_Query1.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Functionality{% endblock %}
{% block content %}
<h1>MAGIS AIR FLIGHT SCHEDULES FUNCTIONALITY</h1>
<table>
    <tr>
        <th>Flight</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Departure</th>
        <th>Arrival</th>
        <th>Duration</th>
    </tr>
    {% for i in data %}
    <tr>
        <td>{{ i.flight_id }}</td>
        <td>{{ i.Origin }}</td>
        <td>{{ i.Destination }}</td>
        <td>{{ i.Departure }}</td>
        <td>{{ i.Arrival }}</td>
        <td>{{ i.Duration }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
<p><a href="{%url 'FlightRoutes:location-table'%}">Check Locations</a></p>
{% endblock %} 

MagisAir/FlightRoutes/templates/FlightRoutes/flights.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Flights {% endblock %}
{% block content %}
<h1>MAGIS Air Flights</h1>
<table>
    <tr>
        <th>Flight ID</th>
        <th>Flight Route</th>
        <th>Departure Date and Time</th>
        <th>Arrival Date and Time</th>
    </tr>
    {% for object in flights %}
    <tr>
        <td>{{ object.flight_id }}</td>
        <td><a href="{%url 'FlightRoutes:route-table' %}">{{ object.flt_route }}</a></td>
        <td>{{ object.flt_datetime_departure }}</td>
        <td>{{ object.flt_datetime_arrival }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'FlightRoutes:flight-add'%}">Add a Flight</a></p>
<p><a href="{%url 'FlightRoutes:location-table'%}">Check Locations</a></p>
<p><a href="{%url 'FlightRoutes:route-table'%}">Check Routes</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightRoutes:SQL_Query1'%}">Check Flight Schedules Functionality</a></p>
{% endblock %} 

MagisAir/FlightRoutes/templates/FlightRoutes/flightsCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add Flight {% endblock %} 
{% block content %}
    <h1>Add a New Flight</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Flight">
    </form>
{% endblock %}

MagisAir/FlightRoutes/templates/FlightRoutes/locations.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Locations {% endblock %}
{% block content %}
<h1>MAGIS Air Locations</h1>
<table>
    <tr>
        <th>Location ID</th>
        <th>Location Name</th>
    </tr>
    {% for object in locations %}
    <tr>
        <td>{{ object.location_id }}</td>
        <td>{{ object.loc_name }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'FlightRoutes:location-add'%}">Add a Location</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
<p><a href="{%url 'FlightRoutes:route-table'%}">Check Routes</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightRoutes:SQL_Query1'%}">Check Flight Schedules Functionality</a></p>
{% endblock %} 

MagisAir/FlightRoutes/templates/FlightRoutes/locationsCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add Location {% endblock %} 
{% block content %}
    <h1>Add a New Location</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Location">
    </form>
{% endblock %}

MagisAir/FlightRoutes/templates/FlightRoutes/routes.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Routes {% endblock %}
{% block content %}
<h1>MAGIS Air Routes</h1>
<table>
    <tr>
        <th>Route ID</th>
        <th>Route Origin</th>
        <th>Route Destination</th>
        <th>Route Price</th>
    </tr>
    {% for object in routes %}
    <tr>
        <td>{{ object.route_id }}</td>
        <td><a href="{%url 'FlightRoutes:location-table'%}">{{ object.rt_origin }}</a></td>
        <td><a href="{%url 'FlightRoutes:location-table'%}">{{ object.rt_destination }}</a></td>
        <td>{{ object.rt_price }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'FlightRoutes:route-add'%}">Add a Route</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
<p><a href="{%url 'FlightRoutes:location-table'%}">Check Locations</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightRoutes:SQL_Query1'%}">Check Flight Schedules Functionality</a></p>
{% endblock %} 

MagisAir/FlightRoutes/templates/FlightRoutes/routesCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add Route {% endblock %} 
{% block content %}
    <h1>Add a New Route</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Route">
    </form>
{% endblock %}

MagisAir/FlightRoutes/templates/FlightRoutes/successfullyAdded.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air {% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'details_style.css' %}">
<h1>Your Data was successfully added</h1>
</table>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
<p><a href="{%url 'FlightRoutes:location-table'%}">Check Locations</a></p>
<p><a href="{%url 'FlightRoutes:route-table'%}">Check Routes</a></p>
{% endblock %} 