MagisAir/CrewAssignments/urls.py
from django.urls import path

from. views import (CrewMemberListView, CrewRoleListView,
                    CrewAssignmentListView, CrewAssignmentCreateView,
                    CrewAssignmentDetailView, CrewRoleCreateView,
                    CrewRoleDetailView, CrewMemberCreateView,
                    CrewMemberDetailView, SQL_Query2)

urlpatterns = [
    path('members', CrewMemberListView.as_view(), name='crewMember-table'),
    path('roles', CrewRoleListView.as_view(), name='crewRole-table'),
    path('assignments', CrewAssignmentListView.as_view(), name='crewAssignment-table'),
    path('members/add', CrewMemberCreateView.as_view(), name='crewMember-add'),
    path('roles/add', CrewRoleCreateView.as_view(), name='crewRole-add'),
    path('assignments/add', CrewAssignmentCreateView.as_view(), name='crewAssignment-add'),
    path('members/<pk>_added', CrewMemberDetailView.as_view(), name='added-member'),
    path('roles/<pk>_added', CrewRoleDetailView.as_view(), name='added-role'),
    path('assignments/<pk>_added', CrewAssignmentDetailView.as_view(), name='added-assignment'),
    path('SQLQuery2', SQL_Query2, name='SQL_Query2')
]

app_name='CrewAssignments'

MagisAir/FlightBooking/urls.py
from django.urls import path

from. views import (AdditionalitemListView, BookingAdditionalitemListView,
                    BookingListView, PassengerListView, AdditionalitemCreateView,
                    BookingAdditionalitemCreateView, BookingCreateView, PassengerCreateView,
                    AdditionalitemDetailview, BookingAdditionalitemDetailview, BookingDetailView,
                    PassengerDetailview)

urlpatterns = [
    path('passengers', PassengerListView.as_view(), name='passenger-table'),
    path('bookings', BookingListView.as_view(), name='booking-table'),
    path('addItems', AdditionalitemListView.as_view(), name='addItem-table'),
    path('bookingAddItems', BookingAdditionalitemListView.as_view(), name='bookingAddItem-table'),
    path('passengers/add', PassengerCreateView.as_view(), name='passenger-add'),
    path('bookings/add', BookingCreateView.as_view(), name='booking-add'),
    path('addItems/add', AdditionalitemCreateView.as_view(), name='addItem-add'),
    path('bookingAddItems/add', BookingAdditionalitemCreateView.as_view(), name='bookingAddItem-add'),
    path('passengers/<pk>_added', PassengerDetailview.as_view(), name='added-passenger'),
    path('bookings/<pk>_added', BookingDetailView.as_view(), name='added-booking'),
    path('addItems/<pk>_added', AdditionalitemDetailview.as_view(), name='added-addItem'),
    path('bookingAddItems/<pk>_added', BookingAdditionalitemDetailview.as_view, name='added-bookingAddItem')
]

app_name='FlightBooking'

MagisAir/FlightRoutes/urls.py
from django.urls import path

from. views import (LocationListView, FlightListView, RouteListView,
                    LocationCreateView, FlightCreateView, RouteCreateView,
                    LocationDetailview, FlightDetailView, RouteDetailView,
                    SQL_Query1)

urlpatterns = [
    path('locations', LocationListView.as_view(), name='location-table'),
    path('flights', FlightListView.as_view(), name='flight-table'),
    path('routes', RouteListView.as_view(), name='route-table'),
    path('locations/add', LocationCreateView.as_view(), name='location-add'),
    path('flights/add', FlightCreateView.as_view(), name='flight-add'),
    path('routes/add', RouteCreateView.as_view(), name='route-add'),
    path('locations/<pk>_added', LocationDetailview.as_view(), name='added-location'),
    path('flights/<pk>_added', FlightDetailView.as_view(), name='added-flight'),
    path('routes/<pk>_added', RouteDetailView.as_view(), name='added-route'),
    path('SQL_Query1', SQL_Query1, name='SQL_Query1')
]

app_name='FlightRoutes'

MagisAir/MagisAir/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('flights/', include('flights.urls', namespace='flights')),
    path('CrewAssignments/', include('CrewAssignments.urls', namespace='CrewAssignments')),
    path('FlightRoutes/', include('FlightRoutes.urls', namespace='FlightRoutes')),
    path('FlightBooking/', include('FlightBooking.urls', namespace='FlightBooking')),
    path('admin/', admin.site.urls),
]

MagisAir/flights/urls.py
from django.urls import path

from. views import index

urlpatterns = [
    path('', index, name='index')
]

app_name='flights'

MagisAir/FlightBooking/models.py
from django.db import models

# Create your models here.
class Passenger(models.Model):
    passenger_id = models.AutoField(primary_key=True)
    pax_lname = models.CharField(max_length=255)
    pax_fname = models.CharField(max_length=255)
    pax_gender = models.CharField(max_length=2)
    pax_birthdate = models.DateField()

    def __str__(self):
        return '{}'.format(self.passenger_id)
    
    def get_absolute_url(self):
        return reverse('FlightBooking:added-passenger', kwargs={'pk': self.pk})

    class Meta:
        managed = False
        db_table = 'passenger'

class Flight(models.Model):
    flight_id = models.CharField(primary_key=True, max_length=10)
    flt_route = models.ForeignKey('FlightRoutes.Route', models.DO_NOTHING, related_name='+')
    flt_datetime_departure = models.DateTimeField()
    flt_datetime_arrival = models.DateTimeField()

    def __str__(self):
        return '{}'.format(self.flight_id)

    class Meta:
        managed = False
        db_table = 'flight'

class Booking(models.Model):
    bkg_passenger = models.OneToOneField('Passenger', models.DO_NOTHING, primary_key=True)
    bkg_flight = models.ForeignKey('Flight', models.DO_NOTHING, related_name='Flight')
    bkg_bookingdate = models.DateField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('FlightBooking:added-booking', kwargs={'pk': self.pk})
    
    class Meta:
        managed = False
        db_table = 'booking'
        unique_together = (('bkg_passenger', 'bkg_flight'),)

class Additionalitem(models.Model):
    additionalitem_id = models.AutoField(primary_key=True)
    aitm_item = models.CharField(max_length=255)
    aitm_itemdesc = models.CharField(max_length=255, blank=True, null=True)
    aitm_cost = models.IntegerField()

    def __str__(self):
        return '{}'.format(self.additionalitem_id)
    
    def get_absolute_url(self):
        return reverse('FlightBooking:added-addItem', kwargs={'pk': self.pk})

    class Meta:
        managed = False
        db_table = 'additionalitem'

class BookingAdditionalitem(models.Model):
    bai_passenger = models.OneToOneField('Passenger', models.DO_NOTHING, primary_key=True)
    bai_flight = models.ForeignKey('Flight', models.DO_NOTHING, related_name='+')
    bai_additionalitem = models.ForeignKey(Additionalitem, models.DO_NOTHING, 
                                            related_name='+')
    bai_quantity = models.IntegerField()

    def __str__(self):
        return '{}'.format(self.bai_passenger)
    
    def get_absolute_url(self):
        return reverse('FlightBooking:added-bookingAddItem', kwargs={'pk': self.pk})

    class Meta:
        managed = False
        db_table = 'booking_additionalitem'
        unique_together = (('bai_passenger', 'bai_flight', 'bai_additionalitem'),)

MagisAir/FlightBooking/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from .models import Passenger, Booking, Additionalitem, BookingAdditionalitem

class PassengerListView(ListView):
    model = Passenger
    def get(self, request):
        passengers = Passenger.objects.all()
        return render(request, 'FlightBooking/passengers.html', {
            'passengers': passengers
        })

class BookingListView(ListView):
    model = Booking
    def get(self, request):
        bookings = Booking.objects.all()
        return render(request, 'FlightBooking/bookings.html', {
            'bookings': bookings
        })

class AdditionalitemListView(ListView):
    model = Additionalitem
    def get(self, request):
        additionalItems = Additionalitem.objects.all()
        return render(request, 'FlightBooking/additionalItems.html', {
            'additionalItems': additionalItems
        })

class BookingAdditionalitemListView(ListView):
    model = BookingAdditionalitem
    def get(self, request):
        bookingAddItems = BookingAdditionalitem.objects.all()
        return render(request, 'FlightBooking/bookingAddItems.html', {
            'bookingAddItems': bookingAddItems
        })

class PassengerCreateView(CreateView):
    model = Passenger
    fields = '__all__'
    template_name = 'FlightBooking/passengersCreate.html'

class BookingCreateView(CreateView):
    model = Booking
    fields = '__all__'
    template_name = 'FlightBooking/bookingsCreate.html'

class AdditionalitemCreateView(CreateView):
    model = Additionalitem
    fields = '__all__'
    template_name = 'FlightBooking/additionalitemsCreate.html'

class BookingAdditionalitemCreateView(CreateView):
    model = BookingAdditionalitem
    fields = '__all__'
    template_name = 'FlightBooking/bookingAddItemsCreate.html'

class PassengerDetailview(DetailView):
    model = Passenger
    template_name = 'FlightBooking/successfullyAdded.html'

class BookingDetailView(DetailView):
    model = Booking
    template_name = 'FlightBooking/successfullyAdded.html'

class AdditionalitemDetailview(DetailView):
    model = Additionalitem
    template_name = 'FlightBooking/successfullyAdded.html'

class BookingAdditionalitemDetailview(DetailView):
    model = BookingAdditionalitem
    template_name = 'FlightBooking/successfullyAdded.html'

MagisAir/FlightBooking/templates/FlightBooking/additionalItems.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Additional Items {% endblock %}
{% block content %}
<h1>MAGIS Air Additional Items</h1>
<table>
    <tr>
        <th>Additional Item ID</th>
        <th>Item Name</th>
        <th>Item Description</th>
        <th>Cost</th>
    </tr>
    {% for object in additionalItems %}
    <tr>
        <td>{{ object.additionalitem_id }}</td>
        <td>{{ object.aitm_item }}</td>
        <td>{{ object.aitm_itemdesc }}</td>
        <td>{{ object.aitm_cost }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'FlightBooking:addItem-add'%}">Add an Additional Item</a></p>
<p><a href="{%url 'FlightBooking:passenger-table'%}">Check Passengers</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightBooking:bookingAddItem-table'%}">Check Booking Additional Items</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
{% endblock %} 

MagisAir/FlightBooking/templates/FlightBooking/additionalItemsCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add Item {% endblock %} 
{% block content %}
    <h1>Add a New Item</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Item">
    </form>
{% endblock %}

MagisAir/FlightBooking/templates/FlightBooking/bookingAddItems.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Booking Additional Items {% endblock %}
{% block content %}
<h1>MAGIS Air Booking Additional Items</h1>
<table>
    <tr>
        <th>Passenger ID</th>
        <th>Flight ID</th>
        <th>Additional Item ID</th>
        <th>Quantity</th>
    </tr>
    {% for object in bookingAddItems %}
    <tr>
        <td><a href="{%url 'FlightBooking:passenger-table'%}">{{ object.bai_passenger }}</a></td>
        <td><a href="{%url 'FlightRoutes:flight-table'%}">{{ object.bai_flight }}</a></td>
        <td><a href="{%url 'FlightBooking:addItem-table'%}">{{ object.bai_additionalitem }}</a></td>
        <td>{{ object.bai_quantity }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'FlightBooking:bookingAddItem-add'%}">Add a Booking Additional Item</a></p>
<p><a href="{%url 'FlightBooking:passenger-table'%}">Check Passengers</a></p>
<p><a href="{%url 'FlightBooking:addItem-table'%}">Check Additional Items</a></p>
<p><a href="{%url 'FlightBooking:bookingAddItem-table'%}">Check Booking Additional Items</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
{% endblock %} 

MagisAir/FlightBooking/templates/FlightBooking/bookingAddItemsCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add Item {% endblock %} 
{% block content %}
    <h1>Add a New Booking Item</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save Booking Item">
    </form>
{% endblock %}

MagisAir/FlightBooking/templates/FlightBooking/bookings.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Bookings {% endblock %}
{% block content %}
<h1>MAGIS Air Bookings</h1>
<table>
    <tr>
        <th>Passenger ID</th>
        <th>Flight ID</th>
        <th>Booking Date</th>
    </tr>
    {% for object in bookings %}
    <tr>
        <td><a href="{% url 'FlightBooking:passenger-table'%}">{{ object.bkg_passenger }}</a></td>
        <td><a href="{%url 'FlightRoutes:flight-table'%}">{{ object.bkg_flight }}</a></td>
        <td>{{ object.bkg_bookingdate }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'FlightBooking:booking-add'%}">Add a Booking</a></p>
<p><a href="{% url 'FlightBooking:passenger-table'%}">Check Passengers</a></p>
<p><a href="{%url 'FlightBooking:addItem-table'%}">Check Additional Items</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
{% endblock %} 

MagisAir/FlightBooking/templates/FlightBooking/bookingsCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add Booking {% endblock %} 
{% block content %}
    <h1>Add a New Booking</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Booking">
    </form>
{% endblock %}

MagisAir/FlightBooking/templates/FlightBooking/passengers.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air Passengers {% endblock %}
{% block content %}
<h1>MAGIS Air Passengers</h1>
<table>
    <tr>
        <th>Passenger ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Birth Date</th>
        <th>Gender</th>
    </tr>
    {% for object in passengers %}
    <tr>
        <td>{{ object.passenger_id }}</td>
        <td>{{ object.pax_fname }}</td>
        <td>{{ object.pax_lname }}</td>
        <td>{{ object.pax_birthdate }}</td>
        <td>{{ object.pax_gender }}</td>
    </tr>
    {% endfor %}
</table>
<p><a href="{%url 'FlightBooking:passenger-add'%}">Add a Passenger</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightBooking:addItem-table'%}">Check Additional Items</a></p>
<p><a href="{%url 'FlightBooking:bookingAddItem-table'%}">Check Booking Additional Items</a></p>
<p><a href="{%url 'CrewAssignments:crewAssignment-table'%}">Check Assignments</a></p>
<p><a href="{%url 'FlightRoutes:flight-table'%}">Check Flights</a></p>
{% endblock %} 

MagisAir/FlightBooking/templates/FlightBooking/passengersCreate.html
{% extends 'base.html' %}
{% load static %} 
{% block title %} Add Passenger {% endblock %} 
{% block content %}
    <h1>Add a New Passenger</h1>    
    <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save New Passenger">
    </form>
{% endblock %}

MagisAir/FlightBooking/templates/FlightBooking/successfullyAdded.html
{% extends 'base.html' %}
{% load static %} 

{% block title %} MAGIS Air {% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'details_style.css' %}">
<h1>Your Data was successfully added</h1>
</table>
<p><a href="{% url 'FlightBooking:passenger-table'%}">Check Passengers</a></p>
<p><a href="{%url 'FlightBooking:booking-table'%}">Check Bookings</a></p>
<p><a href="{%url 'FlightBooking:addItem-table'%}">Check Additional Items</a></p>
<p><a href="{%url 'FlightBooking:bookingAddItem-table'%}">Check Booking Additional Items</a></p>
{% endblock %} 